server:
  port: 10010
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: mouse-zookeeper

#zookeeper配置
zookeeper:
  connect-string: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
  session-timeout-ms: 5000
  connection-timeout-ms: 3000
