spring:
  application:
    name: mouse-sentinel
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 10003
  servlet:
    context-path: /mouse-sentinel

