spring:
  application:
    name: mouse-gateway
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
  cloud:
    gateway:
      routes:
        - id: mouse-product
          uri: lb://mouse-product
          predicates:
            - Path=/mouse-product/product/**
        - id: mouse-order
          uri: lb://mouse-order
          predicates:
            - Path=/mouse-order/order/**
  zipkin:
    base-url: http://localhost:9411/
server:
  port: 8888
