spring:
  application:
    name: mouse-account
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
  zipkin:
    base-url: http://localhost:9411/
server:
  port: 10004
  servlet:
    context-path: /mouse-account
# seata 配置
seata:
  # 使用哪个事务组
  tx-service-group: my_test_tx_group
  application-id: ${spring.application.name:mouse-account}
